# Generated by Django 3.1.7 on 2021-06-30 11:21

from django.db import migrations, models
import images_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0007_auto_20210502_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=1, null=True, upload_to=images_api.models.nameFile),
        ),
    ]
