# Generated by Django 3.1.7 on 2021-06-30 12:10

from django.db import migrations, models
import images_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0008_auto_20210630_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=images_api.models.nameFile),
        ),
    ]
