# Generated by Django 3.1.7 on 2021-07-02 11:38

from django.db import migrations, models
import images_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0012_auto_20210702_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagename',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=images_api.models.nameFile),
        ),
    ]
